### ISSUE TITLE
GhostKit animate on scroll does NOT seem to be working with Lazy blocks

### ISSUE THREAD

**Issue by kifahhk** [nk-o/ghostkit#101]
To reproduce:
- Add any lazy block with custom code 
- Enable `Animate on scroll` under support section in the side bar
- Create a page with some content and add the created block somewhere in the bottom
- Choose `fade` effect from the side bar
- Update and try to scroll down 

Expected:
The block to fadeIn on scroll 

Results: 
The block does not animate

Running latest Wordpress: **5.4.2**
With
Ghost Kit **2.13.2**
Lazy Blocks **2.0.9**

_P.s: GhostKit `Animate on scroll` works with default Gutenberg blocks_

**Am I missing anything here?** 
BTW: I like the simplicity of your plugins.

**Comment by kifahhk** [comment]
@nk-o 
This happens only if I filter out the wrapper
```
<?php

// disable block frontend wrapper.
add_filter( 'lazyblock/[myblockid]/frontend_allow_wrapper', '__return_false' );

?>
```
Is there any workaround for this?

**Comment by nk-o** [comment]
Hey @kifahhk 

In the block wrapper, we add our own attributes, including Lazy Blocks attributes.

If you remove our wrapper, you should generate your own attributes manually.

https://github.com/nk-o/lazy-blocks/blob/34b0b4a2daf00ea93292a1af6081be76013f3e90/src/classes/class-blocks.php#L1277-L1279
