### ISSUE TITLE
Grid Block not working in IE11 anymore

### ISSUE THREAD

**Issue by silvanarnet** [nk-o/ghostkit#103]
The columns are not shown properly in IE11 like in the Ghostkit Versions before. I don't know whether it's because of de CSS variables or the JS error showing up.

![image](https://user-images.githubusercontent.com/42134096/88782497-f1782c00-d18d-11ea-9e0f-c790529ec83e.png)

**Comment by nk-o** [comment]
Hey.  
  
Thank you for reporting to me. Seems like a problem with CSS Vars Polyfill script.

Created an issue here - nuxodin/ie11CustomProperties#66
