### ISSUE TITLE
carousel looks fine in smaller screens but wrong in bigger screens

### ISSUE THREAD

**Issue by xaviercshp** [nk-o/ghostkit#110]
WP version 5.5.1 ghost kit 2.14.1. here is how it looks and the settings in the admin. the slides show fine on smaller screens but then only one shows on the large screens.

<img width="902" alt="Screen Shot 2020-09-25 at 10 59 52 AM" src="https://user-images.githubusercontent.com/67651875/94283496-13d4be80-ff1f-11ea-9354-83a8a1c2ed4c.png">
<img width="1297" alt="Screen Shot 2020-09-25 at 11 00 03 AM" src="https://user-images.githubusercontent.com/67651875/94283500-1505eb80-ff1f-11ea-88b7-e999136737a0.png">
<img width="269" alt="Screen Shot 2020-09-25 at 11 00 20 AM" src="https://user-images.githubusercontent.com/67651875/94283502-159e8200-ff1f-11ea-9c11-47500179f3f3.png">

**Comment by nk-o** [comment]
Most probably you use a 3rd-party plugin or theme with an old Swiper slider used. Could you provide your site URL, so I can look at the problem?

**Comment by xaviercshp** [comment]
@nk-o soldiersangels.com

**Comment by nk-o** [comment]
Yes, unfortunately, the outdated Swiper version is used in the Events Calendar Pro plugin. We can't somehow change it.

![](https://user-images.githubusercontent.com/14810891/96149232-c346f480-0f11-11eb-9fb0-1ea876b5a68a.png)
