### ISSUE TITLE
Disable "Templates" feature

### ISSUE THREAD

**Issue by firestar300** [nk-o/ghostkit#118]
Hello,

I was looking for a way to hide / deactivate "Templates" feature in the Ghostkit plugin settings and the documentation but I didn't find any answers. In my case, I'm using native Gutenberg block patterns so I don't need this feature. Is there a way to disable this feature ?

Thanks.

**Comment by nk-o** [comment]
Hey.

Something like this one could help you hide admin menu items - https://stackoverflow.com/questions/42934129/hiding-admin-menu-items-in-wordpress
