### ISSUE TITLE
Posibilty to add Content Max Width Inherit from Theme? for alignfull, alignwide grid Blocks

### ISSUE THREAD

**Issue by spencer-j** [nk-o/ghostkit#125]
Would be nice to have this feature like Kadence Row Blocks, so the max Content width inside a alignfull and alignwide Block is taken from $GLOBALS['content_width'].
What do you think?

Greets spencer

**Comment by nk-o** [comment]
Hey @spencer-j 

Can you tell me why do you need this feature? If it is required for a full-width background color/image, you can use our AWB plugin. Example on this page [ghostkit.io/blocks/grid](https://ghostkit.io/blocks/grid/)

**Comment by spencer-j** [comment]
Hello nk-o,
i know the feature with AWB but that ain't working right (it does't stretch the the background outside of content area) in twentytwenty, neve and other themes, even if they support alignfull and alignwide.

greets
spencer

**Comment by nk-o** [comment]
Hey Spencer.  
  
I think we can add support for some popular themes. In our own themes, we add support manually, so everything is fine :)  
  
As a temporary solution - you can use this custom CSS:

```
.ghostkit-grid > .nk-awb.alignfull {
	width: 100vw;
	left: 50%;
	right: 50%;
	margin-left: -50vw;
	margin-right: -50vw;
}
```
