### ISSUE TITLE
Adjusting the Counter count time

### ISSUE THREAD

**Issue by spencer-j** [nk-o/ghostkit#126]
Any way to adjust the up count time?
Greets spencer

**Comment by nk-o** [comment]
Hey Spencer.

Yes, you can change it using jQuery event `prepareCounters` and override some variables https://ghostkit.io/docs/jquery-events/

For example:

```
jQuery( document ).on( 'prepareCounters.ghostkit', function( event, classObject, data ) {
    if ( 'ghostkit' !== event.namespace ) {
        return;
    }

    data.duration = 3000;
} );
```
