### ISSUE TITLE
Button - visited links in wrong color

### ISSUE THREAD

**Issue by Fokusiv** [nk-o/ghostkit#15]
Hello,

First of all great plugin, keep up the good work!

I have a problem where the color of button is wrong when it has been :visited.
Usually this is in the hands of the stylesheet, but when using frameworks such as bootstrap, this is set in their css. I cannot overwrite the color without specifying it to a certain color, and it should be dynamic based on what is chosen in admin.

What I would suggest is :visited (and maybe :active) with the chosen color be added to the class of the button, what do you think?

**Comment by nk-o** [comment]
Hi.

I don't remember that bootstrap has additional styles for `:visited` links. Could you show me an online example with this bug? We already built the theme based on GhostKit and have never faced with such strange thing.

`:active` and `:focus` styles will be added in future updates. Created additional issue https://github.com/nk-o/ghostkit/issues/17
