### ISSUE TITLE
Can't Add Images to Carousel

### ISSUE THREAD

**Issue by billymo** [nk-o/ghostkit#20]
When I try to use the carousel it says "Start writing/typing to choose a block". When I do, the only options are "Preformatted", "List", "Verse", "Heading" and "Quote". I would like to use images. I can not seem to figure out how to get that option.

Thanks in advance.

**Comment by nk-o** [comment]
Try this one:

![image](https://user-images.githubusercontent.com/14810891/48935421-b7667980-ef18-11e8-9642-372290b3acc2.png)

Or this:

![image](https://user-images.githubusercontent.com/14810891/48935434-c3523b80-ef18-11e8-83cc-08e894a907be.png)
