### ISSUE TITLE
I cannot add styles to the Grid block

### ISSUE THREAD

**Issue by alhoseany** [nk-o/ghostkit#34]
Hi nk-o,

This is a great plugin. Thank you for this huge work. I am trying to add some custom styles to the Grid block using the following code:

```
  wp.blocks.registerBlockStyle( 'ghostkit/grid', {
    name: 'slideshow-align-right',
    label: 'Align slide content right',
  } );
```

I see the tyles dropdown in the inspector but when I click on it, the editor crashes.

**Comment by nk-o** [comment]
Hi.

I see this happens also with core/columns blocks. Seems like a Gutenberg bug with blocks, that uses InnerBlocks.

Related issue in Gutenberg repo: https://github.com/WordPress/gutenberg/issues/9897

**Comment by alhoseany** [comment]
ok, Thank you.
Is there is any way to add a custom class to the grid without using the custom class in the advanced panel?

**Comment by nk-o** [comment]
You can try Ghost Kit `Variants`, but most probably it will be deprecated in future updates in favor of `Styles` feature of Gutenberg. See FAQ on how to add it: https://wordpress.org/plugins/ghostkit/#how%20to%20extend%20existing%20blocks
