### ISSUE TITLE
event-stream needs to be removed

### ISSUE THREAD

**Issue by skorasaurus** [nk-o/ghostkit#48]
While trying to build ghostkit, I found that: 

event-stream is a dependency of [gulp-vinyl-zip](https://github.com/joaomoreno/gulp-vinyl-zip/issues/15) 

event-stream is no longer available after it was discovered that malware had slipped into it. 

See https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident
and https://github.com/dominictarr/event-stream/issues/116

**Comment by nk-o** [comment]
Interesting... Thank you for info. I'll check alternatives for zip functionality.
