### ISSUE TITLE
Setting of content width inside alignfull grid block

### ISSUE THREAD

**Issue by spencer-j** [nk-o/ghostkit#51]
Would be great if there would be an option at grid row/section where the nested columns have a maximum width setting. Like section structure setting under  Maximum Content Width" in Otter blocks... but better set only boxed content -> default container width or individual max content in px/%/vw . So there is no need to nest row/section blocks
Regards Spencer

**Comment by spencer-j** [comment]
Maybe it would be a sufficient solution if the "Horizontal Alignment" would stay visible even if its just 1 Column, so the functionality could be simulated with the setting of the "column Size" and "Horizontal Alignment" set to justify-content-center
At the moment i need to set 2 or more columns set the justify-content-center setting and go back and set the columns back to 1.
Hope its somehow understandable what i mean.
What do you think?
Thanks Spencer

**Comment by nk-o** [comment]
Hey.

Yes, looks like a bug, these options should appear. Also with `FullHeight` option in PRO addon vertical align should be visible.

**Comment by nk-o** [comment]
Align was fixed, max-width option for columns will not be added.
