### ISSUE TITLE
Unable to add search query to maps element

### ISSUE THREAD

**Issue by traed** [nk-o/ghostkit#56]
The API key is accepted and map loads correctly without a search query. When I try to enter a search query for either the map or for markers I get an error message that the map didn't load correctly.

Wordpress version: 5.2.1
GhostKit version: 2.4.2

**Comment by nk-o** [comment]
Maybe your API key is limited? Search is working for me:

![image](https://user-images.githubusercontent.com/14810891/60295204-c9cfe800-992b-11e9-937d-633669d30c44.png)
