### ISSUE TITLE
Syntax Error in script.min.js in old IE + Edge Bug

### ISSUE THREAD

**Issue by spencer-j** [nk-o/ghostkit#59]
line 12 column 17460
Fix: Babel for ES6
Greets spencer

**Comment by nk-o** [comment]
Should be fixed in https://github.com/nk-o/ghostkit/commit/b485516436a030182cd703f2e379338892c91614

The plugin will be updated soon.

**Comment by silvanarnet** [comment]
Do you already know when the update will be available?

**Comment by nk-o** [comment]
@silvanarnet in 1-2 days
