### ISSUE TITLE
Woo Products Lost Formatting

### ISSUE THREAD

**Issue by elusivethemes** [nk-o/ghostkit#60]
Hi,

Ive been building a theme and now since the latest update the woocommerce product blocks seem to have lost my custom styling and dont seem to be working with various other plugins such as image flippers and a plugin that shows reductions as a percentage. 

Any ideas to what has changed which could be causing it please ?

Thanks,

Scott

**Comment by nk-o** [comment]
Hi Scott.

Could you show me screenshots or something, where I can see what exactly happens? If possible, also show me what you expected to see. I need to repeat the bug on the test server.

For now, I'm quite don't understand what formatting are you talking about.

Regards, nK.
