### ISSUE TITLE
1.1 MB of Font-Awesome.js file is a serious Performance Concern

### ISSUE THREAD

**Issue by cassini-mohsin** [nk-o/ghostkit#66]
wp-content/plugins/ghostkit/assets/vendor/font-awesome/all.min.js

this file is of 1.1 MB even compressed. that is a serious performance concern on the webpages.
can you please fix this now I am removing this by Wordpress Asset Manager Plugin manually.

**Comment by nk-o** [comment]
If you don't want to use icons, disable it in _Admin Side Menu > Ghost Kit > Settings > Icons_.
