### ISSUE TITLE
Buttons no target attribute

### ISSUE THREAD

**Issue by Zipbug** [nk-o/ghostkit#73]
The buttons block doesn't give any way to open the link in a new tab. There really isn't a way to edit the target attribute at all other than editing the block as html.

**Comment by nk-o** [comment]
Hi.

This option is not working for you?

<img src="https://user-images.githubusercontent.com/14810891/64672574-8853d100-d474-11e9-8c43-6954983e8f12.png" alt="Button Target Attribute" width="300">
