### ISSUE TITLE
Extend grid block

### ISSUE THREAD

**Issue by nikwins** [nk-o/ghostkit#74]
First of all I really like your plugin and can't see why it's user base is still pretty small. I will definitely recommend it to friends.

So now to my problem. Currently there is no option to tell if the grid items should be in the layout (container) or full-width. I would like to have a switch on the parent grid block, maybe just call it "full-width" that can be toggled on or off. The standard should be off imo. If it's off, the `.ghostkit-grid` container should get an extra class, something like `ghostkit-grid--layout` and have an extra div inside that wraps all other content in it. This would allow for grid systems like bootstrap e.g. to work correctly. If full-width is on, the columns would just span across the whole viewport, if it's off, users could style the `.ghostkit-grid` container to be the layout container and the new div inside to be row. The columns inside would then be the layout columns.
This would boost the flexibility of the grid block alot imo.

Let me know what you think about this.

**Comment by nk-o** [comment]
Thank you :)

Currently, most of the themes add their own containers over the content. And if the theme add Gutenberg support, most likely added support for `wide` and `full` alignments https://developer.wordpress.org/block-editor/developers/themes/theme-support/#wide-alignment

In the editor it adds these buttons (example from our [Skylith theme](https://demo.nkdev.info/#skylith)):

<img src="https://user-images.githubusercontent.com/14810891/64947549-eec65e00-d87d-11e9-9b84-c1d46fdfecf7.png" width="300" />

So, I don't think, that separate `fullwidth` option on the Grid will be good solution.

Also, if you just want to add `fullwidth` background on the grid and keep columns to show in the container, you can use our AWB plugin. Example on this page https://ghostkit.io/blocks/grid/

**Comment by nikwins** [comment]
Ahh okay I see. I didn't know of the wide and full alignment options. Added them to my theme and now I have all I needed. Thanks a lot! :)
