### ISSUE TITLE
Ghostkit Grid broken with Gutenberg 7.2.0

### ISSUE THREAD

**Issue by silvanarnet** [nk-o/ghostkit#86]
I've updated Gutenberg to v 7.2.0. The problem is in the backend of wordpress. The columns are not shown beside each other.
![ghostkit](https://user-images.githubusercontent.com/42134096/72326312-47342d80-36af-11ea-849e-5d37e1d894b2.png)

**Comment by nk-o** [comment]
Hi.

Thank you for reporting to me. This bug will be fixed, but overall styles have been changed in the latest Gutenberg. A lot of small issues are still present. Once the new Gutenberg will be added to WordPress, all other issues will be fixed.

Regards, nK.
