### ISSUE TITLE
When does the next release land?

### ISSUE THREAD

**Issue by pascalknecht** [nk-o/ghostkit#92]
Hi @nk-o 
First of all thank you for the great plugin.
We currently have some problems with too many dependencies being enqueued in client sites. We already optimized heavily (used all the filters to remove all dependencies we don't use). But we cannot for instance remove moment.js even though we don't use it. I saw that you improved that in the master branch already which looks awesome. When can we expect to see those changes in the productive plugin?

**Comment by nk-o** [comment]
Hey @pascalknecht. It will be released this week. Please, wait for it. Working on the new features for now :)

![image](https://user-images.githubusercontent.com/14810891/75779495-c3232b80-5d6a-11ea-8500-73cf29c134cf.png)

**Comment by pascalknecht** [comment]
Wow that's perfect. Thank you
