### ISSUE TITLE
Notice: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by traed** [nk-o/ghostkit#95]
I'm getting a Notice: Trying to access array offset on value of type bool on in GhostKit_Assets::enqueue_stored_assets (lines 92 and 97).

Plugin version 2.9.3
WP version: 5.3.2

**Comment by nk-o** [comment]
How can I reproduce this notice? Maybe some specific blocks used, or maybe conflict with 3rd-party plugins?

**Comment by nk-o** [comment]
resolved in https://github.com/nk-o/ghostkit/commit/77af8cfb6886ca8f8908e98481fadeea63c94331
