### ISSUE TITLE
issue in shape devider block

### ISSUE THREAD

**Issue by kevIN-kovaDIA** [nk-o/ghostkit#96]
I had tried shape divider block using ghost kit in Wordpress 5.3.3.

in the backend, I had used shape divider block and cover  block with full-screen option as shown in image 
![Screenshot from 2020-03-23 22-35-48](https://user-images.githubusercontent.com/38972017/77343210-542c6780-6d57-11ea-93d0-72aeebe585b1.png).

but in the front end, it shows an only narrow block for shape divided and cover block as shown in the image![Screenshot from 2020-03-23 22-35-36](https://user-images.githubusercontent.com/38972017/77343369-93f34f00-6d57-11ea-83b6-ef97d230803f.png).

the web page is: https://alakh.co.in

Kindly do needful.

**Comment by nk-o** [comment]
Hi.

So, the core Gutenberg block (Cover) is also doesn't work on your frontend. Most probably the problem in your customizations or in 3rd-party plugins.

Regards, nK.

**Comment by kevIN-kovaDIA** [comment]
Thanks for your reply.

Yes, it could be. Let me try without 3rd party plugin.
