### ISSUE TITLE
Tabs block: tab switching broken in Chrome/FFx when using labels in Japanese/Chinese/...

### ISSUE THREAD

**Issue by Ruzgfpegk** [nk-o/ghostkit#97]
When using the "Tabs" block (version 2.10.2 of the plugin), if a tab label contains Japanese/Chinese/... characters then switching to said tab doesn't work in Chromium-based and Firefox browsers, as the #tab-label link contains non-ASCII characters.
Weirdly enough it does work under Edge, at least the non-Chromium one.

It looks like a function is used inside gutenberg\index.min.js to turn a bunch of non-ascii characters into acceptable ones, but there isn't any fallback for other Unicode characters which are then directly put in the HTML like this:
```html
<a href="#tab-デサント" class="ghostkit-tabs-buttons-item">デサント</a>
```

Whereas Cyrillic, which is supported by the function, becomes as expected:
```html
<a href="#tab-abvgdeyozhzi" class="ghostkit-tabs-buttons-item">абвгдеёжзи</a>
```

I'd suggest to add another function for remaining non-ASCII characters, to cover all cases.
Maybe [Punycode](https://en.wikipedia.org/wiki/Punycode) could be the best candidate to encode these other characters in a "friendly" way, taking relevant portions from [Punycode.js](https://github.com/bestiejs/punycode.js) for instance.

I just started using the GhostKit plugin so I don't know if other blocks would benefit from this additional functionality.
I'll edit or comment this issue if I find other cases.

**Comment by nk-o** [comment]
Please, try to update the plugin to 2.11.0 version. Tabs and accordions now should work with such symbols.

I'm not sure about converting hashes using Punycode, we need to think about it deeper.

**Comment by Ruzgfpegk** [comment]
I updated the plugin and can confirm that tab switching is working now in these cases (tested in Firefox/Chrome/IE/Safari).

Thanks for the quick fix!

If this is enough, I guess there's no need to complicate things further indeed.
